name: Release Cromite CI
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'uazo/cromite SHA'
        required: true
        default: ''
      type:
        description: 'runner? [dev/ci]'
        required: true
        default: 'ci'
      draft:
        description: 'draft? [true/false]'
        required: true
        default: 'false'
      comment:
        description: 'comment'
        required: true
        
env:
  CROMITE_SHA: ${{ github.event.inputs.sha }}
  REMOVEDOCKERSUPPORT: true
  USELOCALIMAGE: true
  COMMENT: ${{ github.event.inputs.comment }}

jobs:
  release:
    runs-on: ${{ github.event.inputs.type }}
    env:
      IS_DRAFT: ${{ github.event.inputs.draft }}
      OUTPUTFILE_ARM: /storage/images/${{ github.event.inputs.sha }}/android/false/arm/
      OUTPUTFILE_ARM64: /storage/images/${{ github.event.inputs.sha }}/android/false/arm64/
      OUTPUTFILE_X64: /storage/images/${{ github.event.inputs.sha }}/android/false/x64/
      OUTPUTFILE_WIN: /storage/images/${{ github.event.inputs.sha }}/win/x64/
      OUTPUTFILE_LIN: /storage/images/${{ github.event.inputs.sha }}/linux/false/lin64/
      OUTPUTFILE_WV_ARM64: /storage/images/${{ github.event.inputs.sha }}/android/false/arm64_webview/

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare container
        run: |
          curl -fsSLO https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip

          cat >|SHA256SUMS <<-EOEF
          75c27caa0008a9cc639beb7506077ad9f32facbffcc4e815e999eaf9588a527e  pup_v0.4.0_darwin_386.zip
          c539a697efee2f8e56614a54cb3b215338e00de1f6a7c2fa93144ab6e1db8ebe  pup_v0.4.0_darwin_amd64.zip
          259eee82c7d7d766f1b8f93a382be21dcfefebc855a9ce8124fd78717f9df439  pup_v0.4.0_dragonfly_amd64.zip
          ba0fe5e87a24cab818e5d2efdd7540714ddfb1b7246600135915c666fdf1a601  pup_v0.4.0_freebsd_386.zip
          1838ef84ec1f961e8009d19a4d1e6a23b926ee315da3d60c08878f3d69af5692  pup_v0.4.0_freebsd_amd64.zip
          6886a9c60a912a810d012610bc3f784f0417999ff7d7df833a0695b9af60395b  pup_v0.4.0_freebsd_arm.zip
          e486b32ca07552cd3aa713cbf2f9d1b6e210ddb51d34b3090c7643f465828057  pup_v0.4.0_linux_386.zip
          ec3d29e9fb375b87ac492c8b546ad6be84b0c0b49dab7ff4c6b582eac71ba01c  pup_v0.4.0_linux_amd64.zip
          c09b669fa8240f4f869dee7d34ee3c7ea620a0280cee1ea7d559593bcdd062c9  pup_v0.4.0_linux_arm64.zip
          ebf70b3c76c02e0202c94af7ef06dcb3ecc866d1b9b84453d43fe01fa5dd5870  pup_v0.4.0_linux_arm.zip
          a98a4d1f3c3a103e8ebe1a7aba9cb9d3cb045003208ca6f5f3d54889a225f267  pup_v0.4.0_linux_mips64le.zip
          8e471cf6cfa118b2497bb3f42a7a48c52d0096107f748f37216855c8ab94f8e5  pup_v0.4.0_linux_mips64.zip
          cfda9375eba65f710e052b1b59893c228c3fc92b0510756bb3f02c25938eee30  pup_v0.4.0_linux_ppc64le.zip
          91a1e07ffb2c373d6053252e4de732f5db78c8eace49c6e1a0ef52402ecdf56c  pup_v0.4.0_linux_ppc64.zip
          fdc9b28a3daac5ad096023e1647292a7eccea6d9b1686f871307dae9f3bd064f  pup_v0.4.0_nacl_386.zip
          c8d3c9b56783bd5a55446f4580e1835606b2b945da2d1417ed509c5927a5f8bc  pup_v0.4.0_nacl_amd64p32.zip
          48c068c4353672528c8c3447a536208b0719f1e6d0f8fab8416b38b63ad0c1d9  pup_v0.4.0_nacl_arm.zip
          7a27497b2f0be95c51bb2cbc25da12efba682c4f766bc5abc5742e9fc8d1eeb0  pup_v0.4.0_netbsd_386.zip
          71a1808eb1b6442aa45d1de9e1c4fca543b2754c1aff5ba3d62b3456f9519691  pup_v0.4.0_netbsd_amd64.zip
          928e6691b11c68ae3f28826848a13dc5c1c9673848fe7cf7f80dd76c9fb6e8a6  pup_v0.4.0_netbsd_arm.zip
          5aca20a9b3264d2fde5a8d32f213c434edf9570ee6fae18953b8fff09d2976e2  pup_v0.4.0_openbsd_386.zip
          e965c6f04b897240d84c60e2c18226deb231a657c5583680f58a61051ff5a100  pup_v0.4.0_openbsd_amd64.zip
          30bc88a1e06606f4f3449af9fbf586f97c2e958677460a72bb1a168f67c4911c  pup_v0.4.0_openbsd_arm.zip
          9d50decf4572292f187cfec84660648d648336bc6109e1f032b1699ba1d28549  pup_v0.4.0_plan9_386.zip
          1b2a6bd2388ddd691ca429497d88b2b047ec8dfb7bce9436925cb2f30632bf8e  pup_v0.4.0_plan9_amd64.zip
          0835de9c10a9e2b3b958b82d148da49eaafc695fe4a018cbaf7bb861b455583f  pup_v0.4.0_solaris_amd64.zip
          01acae220b69fb1ba8477d0e7f4d7669ef5de147966dc819cf75a845af74c5f3  pup_v0.4.0_windows_386.zip
          6755cbd43e94eaf173689e93e914c7056a2249c2977e5b90024fb397f9b45ba4  pup_v0.4.0_windows_amd64.zip
          EOEF

          ( grep -e 'pup_v0\.4\.0_linux_amd64\.zip$' SHA256SUMS | sha256sum --check --strict --warn ; ) || exit
          unzip pup_v0.4.0_linux_amd64.zip && rm pup_v0.4.0_linux_amd64.zip

          BRANCH=$(curl https://github.com/uazo/cromite/branch_commits/$CROMITE_SHA | ./pup -p li.branch:last-child a text{} | xargs)
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Checkout 'uazo/cromite'
        uses: actions/checkout@v7
        with:
            repository: 'uazo/cromite'
            path: 'cromite'
            fetch-depth: 1

      - name: Create release
        shell: bash
        run: |          
          VERSION=v$(cat ${{ env.OUTPUTFILE_ARM64 }}/RELEASE)

          cd cromite/tools

          _gh_cli_version='2.102.0'
          _gh_cli_sha256_checksum='afe49e9affa232faa8212aed035417166f6ade9b9470acb53d4dbd28c0504e8d'
          _gh_cli_release_url="https://github.com/cli/cli/releases/download/v${_gh_cli_version}"
          curl -fsSLo checksums.txt "${_gh_cli_release_url}/gh_${_gh_cli_version}_checksums.txt"
          ( printf -- '%s *checksums.txt\n' "${_gh_cli_sha256_checksum}" | \
              sha256sum --check --strict --warn ; ) || exit
          GH="gh_${_gh_cli_version}_linux_amd64/bin/gh"
          curl -fsSLO "${_gh_cli_release_url}/gh_${_gh_cli_version}_linux_amd64.tar.gz"
          ( grep -e '_linux_amd64\.tar\.gz$' checksums.txt | \
              sha256sum --check --strict --warn ; ) || exit
          tar -zxpf "gh_${_gh_cli_version}_linux_amd64.tar.gz"
          unset -v _gh_cli_release_url _gh_cli_sha256_checksum _gh_cli_version

          echo ${{ secrets.GITHUB_TOKEN }} | $GH auth login --with-token

          echo $COMMENT >note

          $GH release create $VERSION-$CROMITE_SHA --notes-file note -d
          : >|SHA512SUMS

          # android arm
          echo "::group::-------- android arm"
          sudo cp ${{ env.OUTPUTFILE_ARM }}/apks/ChromePublic.apk arm_ChromePublic.apk
          sudo chown runner arm_ChromePublic.apk
          sha512sum >>SHA512SUMS -b arm_ChromePublic.apk &
          echo Uploading arm_ChromePublic
          $GH release upload $VERSION-$CROMITE_SHA arm_ChromePublic.apk
          echo "::endgroup::"

          # android arm64
          echo "::group::-------- android arm64"
          sudo cp ${{ env.OUTPUTFILE_ARM64 }}/apks/ChromePublic.apk arm64_ChromePublic.apk
          sudo chown runner arm64_ChromePublic.apk
          sha512sum >>SHA512SUMS -b arm64_ChromePublic.apk &
          echo Uploading arm64_ChromePublic
          $GH release upload $VERSION-$CROMITE_SHA arm64_ChromePublic.apk
          echo "::endgroup::"

          # android x64
          echo "::group::-------- android x64"
          sudo cp ${{ env.OUTPUTFILE_X64 }}/apks/ChromePublic.apk x64_ChromePublic.apk
          sudo chown runner x64_ChromePublic.apk
          sha512sum >>SHA512SUMS -b x64_ChromePublic.apk &
          echo Uploading x64_ChromePublic
          $GH release upload $VERSION-$CROMITE_SHA x64_ChromePublic.apk
          echo "::endgroup::"

          echo "::group::-------- chrome.size"
          ( cd "$OUTPUTFILE_ARM64/" && sha512sum -b chrome.size ) >>SHA512SUMS &
          test $VERSION-$CROMITE_SHA $OUTPUTFILE_ARM64/chrome.size && \
            $GH release upload $VERSION-$CROMITE_SHA $OUTPUTFILE_ARM64/chrome.size
          echo "::endgroup::"

          echo "::group::-------- ChromePublic.apk.mapping"
          sudo cp ${{ env.OUTPUTFILE_ARM64 }}/apks/ChromePublic.apk.mapping arm64_ChromePublic.apk.mapping
          sha512sum >>SHA512SUMS -b arm64_ChromePublic.apk.mapping &
          $GH release upload $VERSION-$CROMITE_SHA arm64_ChromePublic.apk.mapping
          sudo cp ${{ env.OUTPUTFILE_X64 }}/apks/ChromePublic.apk.mapping x64_ChromePublic.apk.mapping
          sha512sum >>SHA512SUMS -b x64_ChromePublic.apk.mapping &
          $GH release upload $VERSION-$CROMITE_SHA x64_ChromePublic.apk.mapping
          echo "::endgroup::"

          echo "::group::-------- Uploading arm64_ninja_log_trace.html"
          test $OUTPUTFILE_ARM64/ninja_log_trace.html && \
            cp $OUTPUTFILE_ARM64/ninja_log_trace.html arm64_ninja_log_trace.html && \
            $GH release upload $VERSION-$CROMITE_SHA arm64_ninja_log_trace.html && \
            sha512sum >>SHA512SUMS -b arm64_ninja_log_trace.html
          echo "::endgroup::"

          # windows x64
          echo "::group::-------- windows x64"
          mkdir chrome-win/
          cp $OUTPUTFILE_WIN/*.manifest chrome-win/
          cp $OUTPUTFILE_WIN/chrome.dll chrome-win/
          cp $OUTPUTFILE_WIN/chrome.exe chrome-win/
          cp $OUTPUTFILE_WIN/chrome_100_percent.pak chrome-win/
          cp $OUTPUTFILE_WIN/chrome_200_percent.pak chrome-win/
          cp $OUTPUTFILE_WIN/chrome_elf.dll chrome-win/
          cp $OUTPUTFILE_WIN/chrome_proxy.exe chrome-win/
          cp $OUTPUTFILE_WIN/chrome_pwa_launcher.exe chrome-win/
          cp $OUTPUTFILE_WIN/chrome_wer.dll chrome-win/
          cp "/win_sdk/sdks/28000/Windows Kits/10/Redist/D3D/x64/d3dcompiler_47.dll" chrome-win/
          cp $OUTPUTFILE_WIN/elevation_service.exe chrome-win/
          cp "$OUTPUTFILE_WIN/First Run" chrome-win/
          cp $OUTPUTFILE_WIN/icudtl.dat chrome-win/
          cp $OUTPUTFILE_WIN/libEGL.dll chrome-win/
          cp $OUTPUTFILE_WIN/libGLESv2.dll chrome-win/
          cp $OUTPUTFILE_WIN/Logo.png chrome-win/
          cp $OUTPUTFILE_WIN/notification_helper.exe chrome-win/
          cp $OUTPUTFILE_WIN/resources.pak chrome-win/
          cp $OUTPUTFILE_WIN/SmallLogo.png chrome-win/
          cp $OUTPUTFILE_WIN/snapshot_blob.bin chrome-win/
          cp $OUTPUTFILE_WIN/VkICD_mock_icd.dll chrome-win/
          cp $OUTPUTFILE_WIN/VkLayer_khronos_validation.dll chrome-win/
          cp $OUTPUTFILE_WIN/vk_swiftshader.dll chrome-win/
          cp $OUTPUTFILE_WIN/vulkan-1.dll chrome-win/
          cp -r $OUTPUTFILE_WIN/locales chrome-win/locales

          #test chrome-win.zip && rm chrome-win.zip
          zip -r chrome-win.zip chrome-win/

          sha512sum >>SHA512SUMS -b chrome-win.zip &
          echo Uploading chrome-win.zip
          $GH release upload $VERSION-$CROMITE_SHA chrome-win.zip
          echo "::endgroup::"

          TIMESTAMP=$(date +%s -r chrome-win.zip)
          echo >updateurl.txt "browser=chromium;os=windows;architecture=64-bit;timestamp=$TIMESTAMP;editor=uazo;channel=stable;repository=https://github.com/uazo/cromite/releases;download=https://github.com/uazo/cromite/releases/latest/download/chrome-win.zip;version=$(cat $OUTPUTFILE_WIN/RELEASE);revision=1;commit=$CROMITE_SHA"
          sha512sum >>SHA512SUMS -b updateurl.txt
          $GH release upload $VERSION-$CROMITE_SHA updateurl.txt

          ## linux
          echo "::group::-------- linux x64"
          mkdir chrome-lin/
          cp $OUTPUTFILE_LIN/chrome chrome-lin/
          cp $OUTPUTFILE_LIN/chrome_100_percent.pak chrome-lin/
          cp $OUTPUTFILE_LIN/chrome_200_percent.pak chrome-lin/
          cp $OUTPUTFILE_LIN/chrome_crashpad_handler chrome-lin/
          cp $OUTPUTFILE_LIN/chrome-wrapper chrome-lin/
          cp $OUTPUTFILE_LIN/icudtl.dat chrome-lin/
          cp $OUTPUTFILE_LIN/libEGL.so chrome-lin/
          cp $OUTPUTFILE_LIN/libGLESv2.so chrome-lin/
          cp $OUTPUTFILE_LIN/libvulkan.so.1 chrome-lin/
          cp $OUTPUTFILE_LIN/libqt5_shim.so chrome-lin/
          cp $OUTPUTFILE_LIN/libqt6_shim.so chrome-lin/
          cp $OUTPUTFILE_LIN/libvk_swiftshader.so chrome-lin/
          cp -r $OUTPUTFILE_LIN/locales/ chrome-lin/locales
          cp $OUTPUTFILE_LIN/product_logo_48.png chrome-lin/
          cp $OUTPUTFILE_LIN/resources.pak chrome-lin/
          cp $OUTPUTFILE_LIN/snapshot_blob.bin chrome-lin/
          cp $OUTPUTFILE_LIN/chrome_sandbox chrome-lin/

          tar -czvf chrome-lin64.tar.gz chrome-lin/

          sha512sum >>SHA512SUMS -b chrome-lin64.tar.gz &
          echo Uploading chrome-lin64.tar.gz
          $GH release upload $VERSION-$CROMITE_SHA chrome-lin64.tar.gz
          echo "::endgroup::"

          # android arm64 symbols
          echo "::group::-------- arm64 symbols"
          zip arm64_symbols.zip ${{ env.OUTPUTFILE_ARM64 }}/dump_syms \
                                ${{ env.OUTPUTFILE_ARM64 }}/minidump_stackwalk \
                                ${{ env.OUTPUTFILE_ARM64 }}/libchrome.so
          sha512sum >>SHA512SUMS -b arm64_symbols.zip &
          $GH release upload $VERSION-$CROMITE_SHA arm64_symbols.zip
          echo "::endgroup::"

          # android arm64
          echo "::group::-------- android systemwebview arm64"
          sudo cp ${{ env.OUTPUTFILE_WV_ARM64 }}/apks/SystemWebView.apk arm64_SystemWebView.apk
          sudo chown runner arm64_SystemWebView.apk

          sudo cp ${{ env.OUTPUTFILE_WV_ARM64 }}/apks/SystemWebViewShell.apk arm64_SystemWebViewShell.apk
          sudo chown runner arm64_SystemWebViewShell.apk

          sha512sum >>SHA512SUMS -b arm64_SystemWebView.apk arm64_SystemWebViewShell.apk &
          echo Uploading arm64_SystemWebView
          $GH release upload $VERSION-$CROMITE_SHA arm64_SystemWebView.apk
          $GH release upload $VERSION-$CROMITE_SHA arm64_SystemWebViewShell.apk
          echo "::endgroup::"

          wait || true
          $GH release upload $VERSION-$CROMITE_SHA SHA512SUMS
          $GH release edit $VERSION-$CROMITE_SHA -t $VERSION-$CROMITE_SHA

          if [ $IS_DRAFT == "false" ]; then
            $GH release edit $VERSION-$CROMITE_SHA --draft=false
          fi


